// Created by iWeb 3.0.4 local-build-20111125

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,183),url:'Nonlinear_Microscopy_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Nonlinear_Microscopy_files/stroke_1.png'},{rect:new IWRect(1,-1,239,2),url:'Nonlinear_Microscopy_files/stroke_2.png'},{rect:new IWRect(240,-1,2,2),url:'Nonlinear_Microscopy_files/stroke_3.png'},{rect:new IWRect(240,1,2,183),url:'Nonlinear_Microscopy_files/stroke_4.png'},{rect:new IWRect(240,184,2,2),url:'Nonlinear_Microscopy_files/stroke_5.png'},{rect:new IWRect(1,184,239,2),url:'Nonlinear_Microscopy_files/stroke_6.png'},{rect:new IWRect(-1,184,2,2),url:'Nonlinear_Microscopy_files/stroke_7.png'}],new IWSize(241,185)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,183),url:'Nonlinear_Microscopy_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Nonlinear_Microscopy_files/stroke_9.png'},{rect:new IWRect(1,-1,239,2),url:'Nonlinear_Microscopy_files/stroke_10.png'},{rect:new IWRect(240,-1,2,2),url:'Nonlinear_Microscopy_files/stroke_11.png'},{rect:new IWRect(240,1,2,183),url:'Nonlinear_Microscopy_files/stroke_12.png'},{rect:new IWRect(240,184,2,2),url:'Nonlinear_Microscopy_files/stroke_13.png'},{rect:new IWRect(1,184,239,2),url:'Nonlinear_Microscopy_files/stroke_14.png'},{rect:new IWRect(-1,184,2,2),url:'Nonlinear_Microscopy_files/stroke_15.png'}],new IWSize(241,185)),reflection_0:new IWReflection({opacity:0.50,offset:1.00})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Nonlinear_Microscopy_files/Nonlinear_MicroscopyMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
